// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Thu Apr 13 02:16:57 2023

cpu_core cpu_core_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.instruction(instruction_sig) ,	// input [31:0] instruction_sig
	.imem_read(imem_read_sig) ,	// output  imem_read_sig
	.imem_addr(imem_addr_sig) ,	// output [31:0] imem_addr_sig
	.dmem_read_ena(dmem_read_ena_sig) ,	// output  dmem_read_ena_sig
	.dmem_write_ena(dmem_write_ena_sig) ,	// output  dmem_write_ena_sig
	.dmem_addr(dmem_addr_sig) ,	// output [31:0] dmem_addr_sig
	.dmem_data_in(dmem_data_in_sig) ,	// input [31:0] dmem_data_in_sig
	.dmem_data_out(dmem_data_out_sig) 	// output [31:0] dmem_data_out_sig
);

